### ISSUE TITLE
Bump-mem-limit is annoying.

### ISSUE THREAD

**Issue by mimullin-bbry** [libbpf/libbpf-rs#159]
See: https://github.com/libbpf/libbpf/issues/369

@anakryiko If this issue is addressed in libbpf will libbpf-sys and libbpf-rs get this functionality "for free" or will a similar change need to be made to the rust libbpf ecosystem?

**Comment by anakryiko** [comment]
That's the immediate next thing I'm adding to libbpf, btw. We should probably make libbpf-rs opt-in into libbpf 1.0 mode starting from the next release? If that will be the case, then yes, everything will happen automatically. libbpf will probably expose additional API to specify the RLIMIT value itself (by default it will be set to infinity), so we might want to expose that to libbpf-rs, but otherwise libbpf-rs shouldn't do anything extra.

**Comment by mimullin-bbry** [comment]
Looks like from your change to libbpf (https://github.com/kernel-patches/bpf/commit/2b675ff210fbc2032824029cc16bb44b51ac0614) we will not need any changes to libbpf-rs.  If a new API is added to libbpf to specify the rlimit we can create a new ticket to track the work of exposing that API in libbpf-rs.
