### ISSUE TITLE
setting XDP modes

### ISSUE THREAD

**Issue by kckeiks** [libbpf/libbpf-rs#185]
Hello,

I see that `bpf_program__attach_xdp` is used to attach programs to XDP but how do we specify the mode (generic, native, offloaded)? Seems like generic is the default, is that right?

I found this set of [patches](https://lwn.net/ml/bpf/20200713051230.3250515-1-andriin@fb.com/) and it looks like the bpf_link-based API was added to attach BPF XDP programs through
some low level (BPF_LINK_CREATE) command. Does this mean that libbpf does not provide a way to specify the mode when using the bpf link based attachment?
I'm aware that there are other means to attach (using netlink I think) and specify the mode but they wont leverage the bpf_link infrastructure. 

I'm new to BPF so any guidance would be great. I loving this project btw.

**Comment by insearchoflosttime** [comment]
Hello! Welcome to bpf and to libbpf-rs! That's a great question - right now, libbpf does not support a way to specify the mode when attaching a program to XDP. There will need to be a function like `bpf_program__attach_xdp_opts` that will take in opts where you can specify the mode.

**Comment by anakryiko** [comment]
You can specify XDP flags (XDP_FLAGS_HW_MODE|XDP_FLAGS_DRV_MODE|XDP_FLAGS_SKB_MODE) when using BPF_LINK_CREATE command directly through link_create.flags attribute. Unfortunately higher-level libbpf API (bpf_program__attach_xdp()) doesn't provide a way to do this, but I think that's because in practice you shouldn't really need that. When no flags are specified, kernel chooses between DRV_MODE or SKB_MODE depending on which mode device supports (DRV_MODE is preferred, if available; with fallback to SKB generic mode). This is the best behavior, most probably, unless you want to enforce that it is always DRV_MODE and fail otherwise.

**Comment by kckeiks** [comment]
Thank you both. Sounds like adding functionality to this library to specify the mode isn't necessary then but if you think it would be a good addition, I would be glad to have a go at it. Cheers.
