### ISSUE TITLE
Interact and load bpf program object without skeleton

### ISSUE THREAD

**Issue by Icegrave0391** [libbpf/libbpf-rs#230]
Hi, I'm new to eBPF and libbpf-rs. 

I would like to build the BPF program by using `clang` (to generate the BPF object file), and I noticed there is such a workflow ([alternative workflow](https://docs.rs/libbpf-rs/0.17.0/libbpf_rs/index.html#alternate-workflow)) post on the official document which indicates to use a normal rust project and libbpf-rs directly to interact and load the BPF program.

I'd like to know if there is an example or demo that shows the exact way to do such a thing (i.e., setup program, maps, and global variables for BPF program)? The only example I found is to use build.rs to generate the skeleton file.

**Comment by insearchoflosttime** [comment]
Hi @Icegrave0391. libbpf-cargo supports building a BPF program into an object file without generating the skeleton (added in this PR https://github.com/libbpf/libbpf-rs/pull/223). I think you can then use the ObjectBuilder::open and load functions to open and load it yourself, instead of opening and loading it through the skeleton. There isn't an example or demo in this repo that does this (the examples/demos we have use the skeleton interface), but [the test_object_reuse_pined_map test ](https://github.com/libbpf/libbpf-rs/blob/6f14ed033c560cf10a9dfb3dfb22f5dc5d3cf631/libbpf-rs/tests/test.rs#L417) might be a useful example to look at.
