### ISSUE TITLE
Preserve errno in set_print()

### ISSUE THREAD

**Issue by insearchoflosttime** [libbpf/libbpf-rs#256]
We need to preserve the errno and set it back after the callback function is called.

For more context, please see https://github.com/libbpf/libbpf/pull/536

**Comment by danielocfb** [comment]
I think we are good on this front, given that the upstream change has been merged. I tried adding a test, but I couldn't come up with a way to make it work because `libbpf_print` is not an exported function, so we can't reliably trigger prints without also risking clobbering `errno`.

Anyway, given that `libbpf-rs` doesn't add anything that clobbers `errno` itself I think we are in the clear from the `libbpf-rs` perspective. All it adds is some dispatching based on the level at which logs were emitted, and a possible [call](https://github.com/libbpf/libbpf-rs/blob/edfa0594072d3280503a1cdd5b3f8c7f80ff53a2/libbpf-rs/src/print.rs#L62) to `vsprintf`. Does that sound reasonable to you, @insearchoflosttime ?
