### ISSUE TITLE
which kernel verion/versions are supported?

### ISSUE THREAD

**Issue by FirstLoveLife** [libbpf/libbpf-rs#688]
Hi all,

As we know, libbpf's API is not stable and might get broken in new kernel releases.

Could you please let me know which kernel versions libbpf aims to support? And which kernel verion/versions libbpf-rs can support now?

**Comment by danielocfb** [comment]
I don't think we can make any claims about the kernel version and it really is not what determines stability of `libbpf-rs`'s API. We are only a thin/idiomatic wrapper around `libbpf`, which to the best of my knowledge doesn't make any claims about supported kernel versions either. In general, it depends on what features you use. https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md seems to provide a good overview of what kernel version various features are available at.

**Comment by danobi** [comment]
I think during <1.0 to 1.0 release, libbpf did break backwards compat. But >1.0, I think it should be stable API. Do you have examples where APIs were broken?

**Comment by FirstLoveLife** [comment]
Thanks @danobi , @danielocfb 

I'm using the 4.19 kernel with the bundled libbpf. However, it doesn't specify for LIBBPF_MAJOR_VERSION/LIBBPF_MINOR_VERSION. Unsure if libbpf-rs supports can it.

**Comment by danielocfb** [comment]
For `libbpf`, we support what it says in [`Cargo.toml`](https://github.com/libbpf/libbpf-rs/blob/234585e2d6172d8642d0d6dd2f3dd1e8fdde11f3/libbpf-rs/Cargo.toml#L29):
https://github.com/libbpf/libbpf-rs/blob/234585e2d6172d8642d0d6dd2f3dd1e8fdde11f3/libbpf-rs/Cargo.toml#L29

So that's [`libbpf-sys-1.3.0+v1.3.0`](https://crates.io/crates/libbpf-sys/1.3.0+v1.3.0), which means `libbpf` `v1.3.0` at a minimum. Yes, `libbpf` had some minor incompatibilities with 1.0, but my understanding is that it has been backwards compatible since then. Kernel 4.19 is old and while I don't know what version of `libbpf` it maps to off hand, it's almost certainly not `1.3.0`.

I would recommend using the `libbpf` that comes vendored with `libbpf-sys`. You could still run into missing kernel features, but that's no different than in your current situation and would only apply to certain features at runtime and is rather easy to test for.
